services:
  php:
    image: php:8.3-fpm
    container_name: php_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
  node:
    image: node:22  
    container_name: node_app
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "5173:5173"
    command: ["npm", "run", "dev"]
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
